package com.parkinglotmanager.model;

import java.time.LocalDateTime;

/**
 * Represents a user-submitted report about parking lot availability.
 * Part of crowdsourced data collection system.
 */
public class UserReport {
    private String reportId;
    private int userId;
    private String lotId;
    private LocalDateTime timestamp;
    private int reportedAvailable;
    private int confidence;
    private String comments;

    /**
     * Constructor for creating a new user report
     */
    public UserReport(String reportId, int userId, String lotId, int reportedAvailable,
            int confidence, String comments) {
        this.reportId = reportId;
        this.userId = userId;
        this.lotId = lotId;
        this.timestamp = LocalDateTime.now();
        this.reportedAvailable = reportedAvailable;
        this.confidence = confidence;
        this.comments = comments;
    }

    /**
     * Constructor for loading from database
     */
    public UserReport(String reportId, int userId, String lotId, LocalDateTime timestamp,
            int reportedAvailable, int confidence, String comments) {
        this.reportId = reportId;
        this.userId = userId;
        this.lotId = lotId;
        this.timestamp = timestamp;
        this.reportedAvailable = reportedAvailable;
        this.confidence = confidence;
        this.comments = comments;
    }

    // Getters and Setters
    public String getReportId() {
        return reportId;
    }

    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getLotId() {
        return lotId;
    }

    public void setLotId(String lotId) {
        this.lotId = lotId;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public int getReportedAvailable() {
        return reportedAvailable;
    }

    public void setReportedAvailable(int reportedAvailable) {
        this.reportedAvailable = reportedAvailable;
    }

    public int getConfidence() {
        return confidence;
    }

    public void setConfidence(int confidence) {
        this.confidence = confidence;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return String.format("UserReport{id='%s', lot='%s', available=%d, confidence=%d%%}",
                reportId, lotId, reportedAvailable, confidence);
    }

    /*
    package com.parkinglotmanager.model;

import java.time.LocalDateTime;

//  Represents a user-submitted report about parking lot fullness.
//  Maps to the 'ParkingReport' table in the database.

public class UserReport {
    private int reportId;       // Maps to parkingReportID (INT)
    private int userId;         // Maps to userID (INT)
    private int lotId;          // Maps to lotID (INT)
    private int fullness;       // Maps to fullness (INT 0-100)
    private LocalDateTime reportTime; // Maps to reportTime (DATETIME)


    //  Constructor for creating a new report (before saving to DB)
    //  ID is 0 because it will be auto-generated by MySQL

    public UserReport(int userId, int lotId, int fullness) {
        this.reportId = 0;
        this.userId = userId;
        this.lotId = lotId;
        this.fullness = fullness;
        this.reportTime = LocalDateTime.now();
    }

 
    //  * Constructor for loading from database

    public UserReport(int reportId, int userId, int lotId, int fullness, LocalDateTime reportTime) {
        this.reportId = reportId;
        this.userId = userId;
        this.lotId = lotId;
        this.fullness = fullness;
        this.reportTime = reportTime;
    }

    // --- Getters and Setters ---

    public int getReportId() {
        return reportId;
    }

    public void setReportId(int reportId) {
        this.reportId = reportId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getLotId() {
        return lotId;
    }

    public void setLotId(int lotId) {
        this.lotId = lotId;
    }

    public int getFullness() {
        return fullness;
    }

    public void setFullness(int fullness) {
        this.fullness = fullness;
    }

    public LocalDateTime getReportTime() {
        return reportTime;
    }

    public void setReportTime(LocalDateTime reportTime) {
        this.reportTime = reportTime;
    }

    @Override
    public String toString() {
        return String.format("Report #%d: Lot %d is %d%% full (Time: %s)",
                reportId, lotId, fullness, reportTime);
    }
}
    */
    
}
